version: '3'

services:
    db:
        environment:
            MYSQL_DATABASE: db
            MYSQL_ROOT_PASSWORD: password
        restart: always
        image: mysql:5.7
        hostname: concepttopography-mysql
        volumes:
            - ${MYSQL_DUMP}:/docker-entrypoint-initdb.d
        ports:
          - 3306:3306
        networks:
            - esnet

    elasticsearch: 
        image: docker.elastic.co/elasticsearch/elasticsearch-oss:6.2.4
        container_name: concepttopography-elasticsearch
        hostname: elasticsearch
        environment:
            - cluster.name=conceptlights
            - http.cors.enabled=true
            - http.cors.allow-origin=http://localhost:8080
            - http.cors.allow-headers=Content-Type, Access-Control-Allow-Headers, Authorization, X-Requested-With
            - http.cors.allow-credentials=true
            - bootstrap.memory_lock=true
            - "ES_JAVA_OPTS=-Xms2g -Xmx2g"
        ports:
            - 9200:9200
        ulimits:
            memlock:
                soft: -1
                hard: -1
        volumes:
            - esdata:/usr/share/elasticsearch/data
        networks:
            - esnet
    indexer:
        build: 
            context: indexer
            dockerfile: Dockerfile.indexer
        image: python:3.6-slim
        restart: always
        volumes:
            - ./indexer:/app
            - ${TEI_DIR}:/app/data
        depends_on:
            - elasticsearch
        networks:
            - esnet
        container_name: concepttopography-indexer
        command: tail -f /dev/null

    concepttopography:
        image: concepttopography:latest
        container_name: concepttopography-web
        build:
            context: .
            dockerfile: Dockerfile
        volumes:
            - .:/app
        hostname: concepttopography
        ports:
            - "8080:8080"
            - "35729:35729"
        networks:
            - esnet
        depends_on:
            - elasticsearch

    kibana:
        image: docker.elastic.co/kibana/kibana-oss:6.2.4
        container_name: concepttopography-kibana
        hostname: kibana
        links:
            - elasticsearch
            - db
        ports:
            - 5601:5601
        networks:
            - esnet
volumes:
  esdata:
    driver: local
  

networks:
    esnet:
